name: GoTask

x-env: &env
  environment:
    - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
    - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    - ASPNETCORE_HTTP_PORTS=80

services:
  app:
    container_name: GoTask.API
    build:
      context: ./src/GoTask.API
      dockerfile: Dockerfile
    <<: *env
    ports:
      - "5284:80"
    networks:
      - backend
    depends_on:
      database:
        condition: service_healthy
  
  database:
    container_name: GoTask.Database
    image: mysql:8.4.6
    environment:
      MYSQL_ROOT_PASSWORD: 2xaW*297hx8R
      MYSQL_DATABASE: gotask
      MYSQL_USER: gotaskuser
      MYSQL_PASSWORD: Password123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s
    <<: *env

volumes:
  db_data:

networks:
  backend: