name: GoTask

x-env: &env
  environment:
    - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
    - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    - ASPNETCORE_HTTP_PORTS=80

services:
  app:
    container_name: GoTask.API
    build:
      context: ./src/GoTask.API
      dockerfile: Dockerfile
    <<: *env
    ports:
      - "5284:80"
    networks:
      - backend
    depends_on:
      - database
  
  database:
    container_name: GoTask.Database
    image: mysql:9.3.0
    environment:
      MYSQL_ROOT_PASSWORD: 2xaW*297hx8R
      MYSQL_DATABASE: gotask
      MYSQL_USER: gotaskuser
      MYSQL_PASSWORD: Password123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    <<: *env

volumes:
  db_data:

networks:
  backend: