# This is a generated file. Not intended for manual editing.
services:
  app:
    build:
      context: "C:\\Users\\phpb2\\Dev\\Rocketseat\\GoTask App\\Back\\GoTask\\src\\\
        GoTask.API"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-musl-x64/dotnet/dotnet"
    - "exec"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "gotask.api:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "C:\\Users\\phpb2\\Dev\\Rocketseat\\GoTask App\\Back\\GoTask\\src\\GoTask.API:/app:rw"
    - "C:\\Users\\phpb2\\Dev\\Rocketseat\\GoTask App\\Back\\GoTask:/src:rw"
    - "C:\\Users\\phpb2\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\phpb2\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.1.4\\\
      LinuxMusl64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\phpb2\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\phpb2\\AppData\\Local\\JetBrains\\Rider2025.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_7_26_15_16_18:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
